# Generated by Django 6.0.3 on 2026-03-05 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestampMillis', models.BigIntegerField()),
                ('moodName', models.CharField(max_length=50)),
                ('moodImageResId', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('triggers', models.JSONField(default=list)),
                ('journal', models.TextField(blank=True, null=True)),
                ('aiReflection', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestampMillis'],
            },
        ),
    ]
