# Generated by Django 6.0.3 on 2026-03-09 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Breathing', 'Breathing Exercise'), ('Grounding', 'Grounding Exercise'), ('Meditation', 'Meditation Session'), ('Focus', 'Focus Timer'), ('SelfCare', 'Self-Care Checklist')], max_length=50)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('Calm', 'Calm'), ('CBT', 'CBT Coach'), ('Listener', 'Listener'), ('General', 'General')], default='General', max_length=20)),
                ('language', models.CharField(default='English', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(default='default_avatar', max_length=100)),
                ('language', models.CharField(default='English', max_length=20)),
                ('text_size', models.CharField(default='Medium', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notification_time', models.TimeField(blank=True, null=True)),
                ('mental_health_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
