# Generated by Django 6.0.3 on 2026-03-11 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_bio_userprofile_goals_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Analysis', max_length=100)),
                ('subtitle', models.CharField(default='How we detected this pattern', max_length=200)),
                ('steps', models.JSONField(default=list)),
                ('confidence_level', models.IntegerField(default=0)),
                ('data_points_count', models.IntegerField(default=0)),
                ('weeks_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
