# Generated by Django 6.0.3 on 2026-03-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITransparency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
