# Generated by Django 6.0.3 on 2026-03-11 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aitransparency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('confidence', models.CharField(max_length=10)),
                ('pattern_type', models.CharField(choices=[('positive', 'Positive'), ('warning', 'Warning'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
