# Generated by Django 6.0.3 on 2026-03-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
