# Generated by Django 6.0.3 on 2026-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_howitworksstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='screen_reader',
            field=models.BooleanField(default=False),
        ),
    ]
