# Generated by Django 6.0.3 on 2026-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_privacypolicy_userprofile_anonymous_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mood_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_insights_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notification_time',
            field=models.CharField(default='9:00 AM', max_length=20),
        ),
    ]
